import '../../../core/constants/business_info.dart';
import '../../../models/pool_table.dart';
import '../../../models/receipt.dart';
import '../widgets/payment_dialog.dart';

/// Builds invoice data for the receipt printer, from the table and the
/// payment result — [PaymentResult] already carries the real subtotal,
/// promo discount, total, and invoice number computed/generated by the
/// backend (see [BillingRepository.submitPayment]) — never fabricated
/// client-side, so a freshly-printed nota always shows the same invoice
/// number a later reprint (from the transaction list) would.
class InvoiceRepository {
  Future<Receipt> generateInvoice(
    PoolTable table,
    PaymentResult payment, {
    required String cashierName,
  }) {
    final now = DateTime.now();
    final start = table.startAt ?? now;
    final duration = now.difference(start);

    return Future.value(
      Receipt(
        businessName: BusinessInfo.name,
        businessAddress: BusinessInfo.address,
        invoiceNumber: payment.invoiceNumber,
        tableLabel: "${_tableNumber(table)} - ${_sessionLabel(table)}",
        periods: const [],
        date: now,
        startAt: start,
        endAt: now,
        totalDuration: duration.isNegative ? Duration.zero : duration,
        subtotal: payment.subtotal,
        discountAmount: payment.discountAmount,
        promoName: payment.promo,
        grandTotal: payment.total,
        paymentMethod: payment.paymentMethod,
        cashierName: cashierName,
      ),
    );
  }

  String _tableNumber(PoolTable table) =>
      table.name.replaceAll(RegExp(r'[^0-9]'), '');

  String _sessionLabel(PoolTable table) {
    switch (table.sessionType) {
      case SessionType.timer:
        return "Timer";
      case SessionType.reguler:
        return "Reguler";
      case null:
        return "-";
    }
  }
}
